-- ============================================================================
-- 0008_installment_payments.sql
-- Installment payment feature for counter orders.
--   • order_installment_plans   : one plan per installment order (total, down payment, paid)
--   • order_installments        : the schedule rows (number, due date, amount, paid, status)
--   • installment_settings      : single-row global configuration
--
-- No enum changes: an active plan leaves orders."PaymentStatus" at its native value;
-- the plan tables are the source of truth for installment state. When the final
-- installment is collected the application flips the order to 'success' (an existing
-- enum value), which makes the existing invoice generator run.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS / conditional seed. Safe to re-run.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.order_installment_plans (
    "Id"                uuid                     NOT NULL DEFAULT gen_random_uuid(),
    "OrderId"           uuid                     NOT NULL,
    "TotalAmount"       numeric(12,2)            NOT NULL DEFAULT 0,
    "DownPayment"       numeric(12,2)            NOT NULL DEFAULT 0,
    "InstallmentCount"  integer                  NOT NULL DEFAULT 0,
    "PaidAmount"        numeric(12,2)            NOT NULL DEFAULT 0,
    "IsCompleted"       boolean                  NOT NULL DEFAULT false,
    "CompletedAt"       timestamp with time zone,
    "CreatedAt"         timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt"         timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_order_installment_plans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_order_installment_plans_orders_OrderId"
        FOREIGN KEY ("OrderId") REFERENCES public.orders("Id") ON DELETE CASCADE
);

-- One plan per order.
CREATE UNIQUE INDEX IF NOT EXISTS "IX_order_installment_plans_OrderId"
    ON public.order_installment_plans ("OrderId");

CREATE TABLE IF NOT EXISTS public.order_installments (
    "Id"                 uuid                     NOT NULL DEFAULT gen_random_uuid(),
    "PlanId"             uuid                     NOT NULL,
    "OrderId"            uuid                     NOT NULL,
    "InstallmentNumber"  integer                  NOT NULL,
    "DueDate"            timestamp with time zone NOT NULL,
    "Amount"             numeric(12,2)            NOT NULL DEFAULT 0,
    "PaidAmount"         numeric(12,2)            NOT NULL DEFAULT 0,
    "Status"             integer                  NOT NULL DEFAULT 0,   -- 0 Pending, 1 PartiallyPaid, 2 Paid
    "PaidAt"             timestamp with time zone,
    "PaidVia"            integer,                                       -- nullable PaymentMode ordinal
    "PaymentReference"   text,
    "ReminderSentAt"     timestamp with time zone,
    "CreatedAt"          timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt"          timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_order_installments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_order_installments_plans_PlanId"
        FOREIGN KEY ("PlanId") REFERENCES public.order_installment_plans("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_order_installments_PlanId_Number"
    ON public.order_installments ("PlanId", "InstallmentNumber");
-- Hot path for reports + the reminder task: find due / overdue rows fast.
CREATE INDEX IF NOT EXISTS "IX_order_installments_Status_DueDate"
    ON public.order_installments ("Status", "DueDate");
CREATE INDEX IF NOT EXISTS "IX_order_installments_OrderId"
    ON public.order_installments ("OrderId");

-- ── Single-row global settings ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.installment_settings (
    "Id"                       uuid                     NOT NULL DEFAULT gen_random_uuid(),
    "AllowInstallments"        boolean                  NOT NULL DEFAULT true,
    "DefaultInstallmentCount"  integer                  NOT NULL DEFAULT 3,
    "MinDownPaymentPercent"    numeric(5,2)             NOT NULL DEFAULT 20,
    "AutoGenerateDueDates"     boolean                  NOT NULL DEFAULT true,
    "DefaultIntervalDays"      integer                  NOT NULL DEFAULT 30,
    "AllowManualModification"  boolean                  NOT NULL DEFAULT true,
    "ReminderDaysBefore"       integer                  NOT NULL DEFAULT 3,
    "CreatedAt"                timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt"                timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_installment_settings" PRIMARY KEY ("Id")
);

INSERT INTO public.installment_settings ("Id")
SELECT gen_random_uuid()
WHERE NOT EXISTS (SELECT 1 FROM public.installment_settings);
