using RioCommerce.Core.Enums;
namespace RioCommerce.Core.DTOs.Leads;

// LeadSource/BlogPostId are trailing optional parameters so every existing call site keeps
// compiling and behaving identically; each capture path now passes its own explicitly.
public record CaptureLeadRequest(string FullName, string Phone, string? City, string? CourseInterest,
    string? Source, string? Message = null,
    LeadSource LeadSource = LeadSource.Other, Guid? BlogPostId = null);

public class LeadRow
{
    public Guid Id { get; set; }
    public string FullName { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string? City { get; set; }
    public string? CourseInterest { get; set; }
    public string? Message { get; set; }
    public string? Source { get; set; }
    public LeadStatus Status { get; set; }
    public DateTime CreatedAt { get; set; }

    // ── Origin ──
    public LeadSource LeadSource { get; set; }
    /// <summary>Set only on blog leads. Null on older blog leads captured before migration 0030.</summary>
    public Guid? BlogPostId { get; set; }
    /// <summary>Resolved from the BlogPost at query time — never a stored copy, so a renamed post
    /// shows its current title here.</summary>
    public string? BlogTitle { get; set; }
    public string? BlogSlug { get; set; }

    // ── CRM columns (list preview only; the full history lives on the detail page) ──
    public DateTime? NextFollowUpAt { get; set; }
    public string? LatestNote { get; set; }
    public DateTime? LatestNoteAt { get; set; }
    public int NoteCount { get; set; }
}

public class LeadFilter
{
    public LeadStatus? Status { get; set; }
    public string? Search { get; set; }
    public int Page { get; set; } = 1;
    public int PageSize { get; set; } = 20;

    /// <summary>Restrict to one origin. Null = every source (the pre-existing behaviour).</summary>
    public LeadSource? Source { get; set; }

    /// <summary>Blog-tab filter: only leads generated by this post. Null = all blogs.</summary>
    public Guid? BlogPostId { get; set; }

    /// <summary>Course/interest filter. Null or blank = any.</summary>
    public string? CourseInterest { get; set; }
}

/// <summary>Per-source totals for the admin tab badges. One query, no client-side counting.</summary>
public record LeadSourceCounts(int HomePage, int Blog, int ContactPage, int Other);

/// <summary>A blog that has produced at least one lead — populates the Blog filter dropdown.</summary>
public record BlogLeadSourceOption(Guid BlogPostId, string Title, int LeadCount);

/// <summary>One entry in a lead's follow-up timeline.</summary>
public record LeadNoteItem(Guid Id, string Body, string CreatedByName, DateTime CreatedAt, DateTime UpdatedAt)
{
    /// <summary>True when the note was edited after it was first written (1s tolerance for save jitter).</summary>
    public bool WasEdited => (UpdatedAt - CreatedAt).TotalSeconds > 1;
}

/// <summary>Everything the admin lead detail view renders — the captured lead plus its CRM state.</summary>
public class LeadDetail
{
    public Guid Id { get; set; }
    public string FullName { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string? City { get; set; }
    public string? CourseInterest { get; set; }
    public string? Message { get; set; }
    public string? Source { get; set; }
    public LeadStatus Status { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? NextFollowUpAt { get; set; }
    public List<LeadNoteItem> Notes { get; set; } = new();
}

public record AddLeadNoteRequest(string Body);

public record UpdateLeadNoteRequest(string Body);
