namespace RioCommerce.Core.Entities;

/// <summary>
/// Single-row global configuration for the counter-order installment feature. Mirrors the
/// single-row pattern used by <c>FranchiseSettings</c> / <c>BannerSliderSettings</c>.
/// </summary>
public class InstallmentSettings : BaseEntity
{
    /// <summary>Master switch — when false the Create Order wizard hides the installment section.</summary>
    public bool AllowInstallments { get; set; } = true;

    /// <summary>Default number of installments pre-filled in the wizard (after the down payment).</summary>
    public int DefaultInstallmentCount { get; set; } = 3;

    /// <summary>Minimum down payment as a percentage of the order total (0–100). 0 = no minimum.</summary>
    public decimal MinDownPaymentPercent { get; set; } = 20m;

    /// <summary>When true, due dates are pre-filled at a fixed cadence (see <see cref="DefaultIntervalDays"/>).</summary>
    public bool AutoGenerateDueDates { get; set; } = true;

    /// <summary>Days between auto-generated due dates.</summary>
    public int DefaultIntervalDays { get; set; } = 30;

    /// <summary>When true, the admin may edit individual installment amounts; when false they're
    /// auto-distributed and locked.</summary>
    public bool AllowManualModification { get; set; } = true;

    /// <summary>Send a reminder this many days before each due date (0 = no reminders).</summary>
    public int ReminderDaysBefore { get; set; } = 3;
}
