using RioCommerce.Core.Entities;
using RioCommerce.Core.Enums;

namespace RioCommerce.Core.DTOs.Installments;

// ── Create-order wizard input ────────────────────────────────────────────────

/// <summary>One row the admin defines in the Create Order installment section.</summary>
public class InstallmentLineInput
{
    public DateTime DueDate { get; set; }
    public decimal Amount { get; set; }
}

/// <summary>Installment block attached to a counter-order create request.</summary>
public class InstallmentPlanInput
{
    public bool Enabled { get; set; }
    public decimal DownPayment { get; set; }
    /// <summary>Mode used to collect the down payment at the counter.</summary>
    public PaymentMode DownPaymentMode { get; set; } = PaymentMode.Cash;
    public List<InstallmentLineInput> Installments { get; set; } = new();
}

// ── Schedule / detail views ──────────────────────────────────────────────────

public record InstallmentRow(
    Guid Id,
    int Number,
    DateTime DueDate,
    decimal Amount,
    decimal PaidAmount,
    decimal PendingAmount,
    InstallmentStatus Status,
    DateTime? PaidAt,
    PaymentMode? PaidVia,
    string? Reference,
    bool IsOverdue);

public class InstallmentPlanView
{
    public Guid PlanId { get; set; }
    public Guid OrderId { get; set; }
    public string OrderNumber { get; set; } = string.Empty;
    public decimal TotalAmount { get; set; }
    public decimal DownPayment { get; set; }
    public decimal PaidAmount { get; set; }
    public decimal OutstandingAmount { get; set; }
    public bool IsCompleted { get; set; }
    public DateTime? CompletedAt { get; set; }
    public List<InstallmentRow> Installments { get; set; } = new();

    /// <summary>The next unpaid installment (for the "Pay Next Installment" action), or null.</summary>
    public InstallmentRow? NextDue { get; set; }
    /// <summary>Friendly payment-status label: "Pending Installments" / "Fully Paid".</summary>
    public string StatusLabel => IsCompleted ? "Fully Paid" : "Pending Installments";
}

/// <summary>Counter collection of a single installment.</summary>
public class CollectInstallmentRequest
{
    public Guid InstallmentId { get; set; }
    public decimal Amount { get; set; }
    public PaymentMode Mode { get; set; } = PaymentMode.Cash;
    public string? Reference { get; set; }
    public DateTime? PaidAt { get; set; }
}

public record CollectInstallmentResult(
    bool Ok,
    string? Error,
    bool PlanCompleted,
    decimal Outstanding,
    Guid? InvoiceId);

// ── Settings ──────────────────────────────────────────────────────────────────

public class InstallmentSettingsModel
{
    public bool AllowInstallments { get; set; } = true;
    public int DefaultInstallmentCount { get; set; } = 3;
    public decimal MinDownPaymentPercent { get; set; } = 20m;
    public bool AutoGenerateDueDates { get; set; } = true;
    public int DefaultIntervalDays { get; set; } = 30;
    public bool AllowManualModification { get; set; } = true;
    public int ReminderDaysBefore { get; set; } = 3;
}

// ── Reports ─────────────────────────────────────────────────────────────────

public enum InstallmentReportKind { Pending, Overdue, Completed, CollectionHistory }

public record InstallmentReportRow(
    Guid OrderId,
    string OrderNumber,
    string StudentName,
    string StudentPhone,
    int? InstallmentNumber,
    DateTime? DueDate,
    decimal Amount,
    decimal PaidAmount,
    decimal PendingAmount,
    InstallmentStatus? Status,
    DateTime? PaidAt,
    PaymentMode? PaidVia,
    decimal PlanTotal,
    decimal PlanOutstanding);

public class InstallmentReportFilter
{
    public InstallmentReportKind Kind { get; set; } = InstallmentReportKind.Pending;
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }
}
